FROM node:18-alpine AS development

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

# FROM node:22-alpine AS production

# WORKDIR /app

# COPY package*.json ./

# RUN npm install --only=production

# COPY . .

# RUN npm run build

# RUN npm install -g http-server

# EXPOSE 5173

# CMD ["http-server", "dist"]
